// Auth
export const SET_AUTH = "SET_AUTH";
export const SET_USER = "SET_USER";
export const LOGOUT = "LOGOUT";
export const STOP_LOADING ="STOP_LOADING"

export const GET_ATTENDANCE_REQUEST = "GET_ATTENDANCE_REQUEST";
export const GET_ATTENDANCE_SUCCESS = "GET_ATTENDANCE_SUCCESS";
export const GET_ATTENDANCE_FAILURE = "GET_ATTENDANCE_FAILURE";