// Auth
export const SET_AUTH = "SET_AUTH";
export const SET_USER = "SET_USER";
export const LOGOUT = "LOGOUT";
export const STOP_LOADING ="STOP_LOADING"

export const GET_ATTENDANCE_REQUEST = "GET_ATTENDANCE_REQUEST";
export const GET_ATTENDANCE_SUCCESS = "GET_ATTENDANCE_SUCCESS";
export const GET_ATTENDANCE_FAILURE = "GET_ATTENDANCE_FAILURE";

export const GET_RECORD_REQUEST = "GET_RECORD_REQUEST";
export const GET_RECORD_SUCCESS = "GET_RECORD_SUCCESS";
export const GET_RECORD_FAILURE = "GET_RECORD_FAILURE";

export const ADD_RECORD = "ADD_RECORD";
export const UPDATE_RECORD = "UPDATE_RECORD";